name: Daily Commit Workflow

on:
  schedule:
    - cron: "5 17 * * *"
  workflow_dispatch:  # optional, lets you trigger manually for testing

jobs:
  daily_commit_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add daily commit by 23f2005383@ds.study.iitm.ac.in
        run: |
          echo "Automated commit on $(date)" >> daily-log.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "chore: daily commit $(date)"
          git push

