name: Daily Scheduled Commit

on:
  schedule:
    - cron: "1 18 * * *" 

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create commit file and log email: 23f2005383@ds.study.iitm.ac.in
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "Run at $TIMESTAMP" >> scheduled_run_log.txt

      - name: Create and push daily commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Automated Daily Update: Log updated'
          files: scheduled_run_log.txt

